name: Dispatch Workflow
 
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'JohnDoe'
      favorite_color:
        description: 'Enter your favorite color'
        required: true
        default: 'blue'
 
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Username and Favorite Color
        run: echo "${{ github.event.inputs.username }} says hello, and favorite color is ${{ github.event.inputs.favorite_color }}"